version: "3.9"
services:
  bot:
    build: .
    environment:
      - JDM_SQLALCHEMY_DATABASE_URI=sqlite+aiosqlite:///db/bot.db'
      - JDM_BOT_TOKEN=${JDM_BOT_TOKEN}
    volumes:
      - db:/db
    restart: unless-stopped
volumes:
  db:
    driver: local
